apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/database
- ../../base/redis
- ../../base/result
- ../../base/vote
- ../../base/worker
- voting-ingress.yaml
- hpa.yaml
commonLabels:
  environment: production
images:
- name: postgres
  newTag: "15-alpine"
- name: redis
  newTag: "alpine"
- name: dockersamples/examplevotingapp_result
  newTag: "latest"
- name: dockersamples/examplevotingapp_vote
  newTag: "latest"
- name: redis
  newTag: "latest"