apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: vote
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80